### ISSUE TITLE
<learn> tag

### ISSUE THREAD

**Issue by athuldevin** [cdwfs/pyaiml#3]
i have devoloped support for learn tag which dynamically learn new categories changed existing learn to load and added eval tag also by making changes in parser and kernel. can i share the code

**Comment by cdwfs** [comment]
Hello! While I appreciate your interest in contributing to this project, please see my responses at https://github.com/creatorrr/pyAIML/issues/2 regarding the <learn> tag.

Short version: my goal for pyaiml was to target AIML as described in the 1.0.1 spec, and I believe its current implementation of the <learn> tag is correct within the context of this goal. If I've misunderstood the spec, please correct me, but [it seems pretty unambiguous](http://www.alicebot.org/TR/2011/#section-learn). I have pretty much moved on from pyaiml at this point, and am vanishingly unlikely to put much work into large-scale improvements and new features; I'd rather just keep it within its original scope, for better or worse. [Other forks](https://github.com/search?utf8=%E2%9C%93&q=pyaiml&type=) of this project may be more interested in pursuing AIML 2.0 compliance; one of them would likely be willing to accept your pull request.

**Comment by athuldevin** [comment]
yes you are right the function for learn in aiml 1.0.1 is to learn urls .later it used to learn categories dynamically , but currently available learn.aiml file from alice bot files says that it Complies with AIML 1.0 Tag Set Specification  and the file is used to learn categories dynamically,
my conclusion is that the current learn in pyaiml is correct but it not used other than initial loading 
if we add new one it will be helpful . because the aiml files release under 1.0 spec uses learn to dynamic teaching and it is awesome because we can teach bot if he do something wrong and it stores in brain
