### ISSUE TITLE
Not compatible with AIML 2.0?

### ISSUE THREAD

**Issue by irfanandratama** [cdwfs/pyaiml#5]
Are you going to update this project so it can compatible with AIML 2.0 syntax?

**Comment by cdwfs** [comment]
Has the AIML 2.0 spec been finalized, or is it still a draft?

...honestly, the answer either way is likely to be "no". I haven't worked on this project in a looooong long time, and bringing it up to speed with over a decade's worth of changes to Python and/or AIML is pretty low on my priority list. I see a number of forks with varying degrees of activity; hopefully one of them will pick up the torch.
